### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by salman65**

### CODE REVIEW

**Comment by hodgef** [comment]
Hey @salman65, thanks for the addition! Could you add this file in `/src/lib/layouts` ? On build, the minified files will be put automatically into the `build` directory.

Thanks!

**Comment by salman65** [comment]
Sure, I will do that.
Thanks

**Comment by salman65** [comment]
I moved the file in src/lib/layouts directory. I also added another layout for sindhi language in another pull request.

**Comment by hodgef** [comment]
Perfect, I'll merge and edit the Readme to give you credit - Thanks!

**Pull request merged**
